### ISSUE TITLE
Retain exit code from wrapped process

### ISSUE THREAD

**Issue by holm** [heroku/heroku-buildpack-redis#13] opened 2016-08-11 06:38 UTC
When wrapping a process with `start-stunnel`, it seems to "eat" the exit code and always exit with 0, no matter what the wrapped processed exited with. This caused issues for us with a release script, since we use any release errors to abort the release.

When we added `start-stunnel`, this caused the release to continue even when our migrations failed.

**Comment by edmorley** [comment] 2017-07-14 17:05
Hi! I'm hoping to switch another stunnel-using buildpack (for memcachier) to the approach used here (since the other buildpack currently uses the daemon approach rather than a wrapper script), so am keen to fix any regressions that might exist with the wrapper script.

~However I can't seem to reproduce this?~

**Edit: I see my mistake now, the below is equivalent to `{./start-stunnel sleep 2} && false`.**

eg:
```bash
$ curl -sSfLO "https://raw.githubusercontent.com/heroku/heroku-buildpack-redis/7c9515c0ba4a5cefe9eb0b41b28b7248f0400ab1/bin/start-stunnel"
$ chmod +x start-stunnel
$ sed -i 's_stunnel4 vendor/stunnel/stunnel.conf_sleep 30_' start-stunnel

$ ./start-stunnel sleep 2
buildpack=stunnel at=stunnel-enabled
buildpack=stunnel at=config-gen-start
./start-stunnel: line 67: bin/stunnel-conf.sh: No such file or directory
buildpack=stunnel at=config-gen-end
buildpack=stunnel at=config-gen-override REDIS_URL
buildpack=stunnel at=stunnel-launched pid=6401 signal=SIGINT
buildpack=stunnel at=app-launched pid=6402
buildpack=stunnel at=app-start
buildpack=stunnel at=stunnel-start
buildpack=stunnel at=app-end
buildpack=stunnel at=exit process=app
buildpack=stunnel at=kill-app pid=6402
./start-stunnel: line 49: kill: (-6402) - No such process
buildpack=stunnel at=wait-app pid=6402
buildpack=stunnel at=kill-aux name=stunnel pid=6401 signal=SIGINT
buildpack=stunnel at=stunnel-end

$ echo $?
0

$ ./start-stunnel sleep 2 && false
...
$ echo $?
1
```
(ignore the error about missing stunnel-conf.sh, this is just from my local machine so it's not expected to exist)

@holm, when you say the release continued, are you using the release phase feature? If so, what command is the `release` entry in your `Procfile` running, and if it is a script, does the script enable bash error on exit?

**Comment by edmorley** [comment] 2018-01-08 22:57
@holm don't suppose you saw the above? :-)

**Comment by holm** [comment] 2018-01-09 07:31
To be honest I can't remember the details anymore. What I am sure of is that the process exited with 0 exit code even though the release failed. We have since switched to our own variant of this buildpack.

**Comment by Davidiusdadi** [comment] 2019-10-16 10:05
i can confirm that the issue remains
> When wrapping a process with start-stunnel, it seems to "eat" the exit code and always exit with 0

**Comment by edmorley** [comment] 2024-05-31 13:02
Closing since this buildpack is now deprecated, as it's no longer required with Redis 6+'s native TLS feature:
https://devcenter.heroku.com/articles/heroku-redis#security-and-compliance

**Closed as not planned by edmorley** 2024-05-31 13:02 UTC
